name:  CI

# on:
#   push:
#     branches:
#       - main
      
#   pull_request:
#     branches:
#       - main
on:
  workflow_dispatch:
     

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Ensure this matches your Node.js version
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: table
    
        severity: 'CRITICAL'
        
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run tests
      run: npm test

    - name : Run Coverage
      run: npm run coverage  



    # - name: Upload coverage to Coveralls
    #   uses: coverallsapp/github-action@v1
    #   with:
    #     path-to-lcov: ./coverage/lcov.info 
        

    - name : SonarQube scan   
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      # with:
      #   args: >
      #     -Dsonar.projectKey=Reactjs-app
      #     -Dsonar.sources=.
      #     -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

 
