
name:  CI

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Ensure this matches your Node.js version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run tests
      run: npm test

    - name: Trivy Secret Scan
      uses: aquasecurity/trivy-action@main
      with:
        scan-type: 'fs' # Scans the filesystem
        ignore-unfixed: true
        format: 'table'
        severity: 'HIGH,CRITICAL'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



 
